export const siteData = [
  {
    id: 0,
    sites: "Princeton Plainsborough",
    perfect: "25%",
    good: "25%",
    bad: "25%",
  },
  {
    id: 1,
    sites: "USCF Medical Center",
    perfect: "20%",
    good: "20%",
    bad: "20%",
  },
  {
    id: 2,
    sites: "NYC Medical Center",
    perfect: "22%",
    good: "22%",
    bad: "22%",
  },
  {
    id: 3,
    sites: "Denver National Hospital",
    perfect: "23%",
    good: "23%",
    bad: "23%",
  },
  {
    id: 4,
    sites: "John Hopkins Hospital",
    perfect: "15%",
    good: "15%",
    bad: "15%",
  },
  {
    id: 5,
    sites: "Chicago Plainsborough",
    perfect: "12%",
    good: "12%",
    bad: "12%",
  },
  {
    id: 6,
    sites: "Chicago National Medical Center",
    perfect: "14%",
    good: "14%",
    bad: "14%",
  },
  {
    id: 7,
    sites: "Chicago University Medical Center",
    perfect: "18%",
    good: "18%",
    bad: "18%",
  },
  {
    id: 8,
    sites: "San-Francisco Medical",
    perfect: "25%",
    good: "25%",
    bad: "25%",
  },
];

export const practiceData = [
  {
    id: 0,
    practice: "NYC Clinics Practice",
    perfect: "25%",
    good: "25%",
    bad: "25%",
  },
  {
    id: 1,
    practice: "Detroit Clinics",
    perfect: "20%",
    good: "20%",
    bad: "20%",
  },
  {
    id: 2,
    practice: "South-West National",
    perfect: "22%",
    good: "22%",
    bad: "22%",
  },
  {
    id: 3,
    practice: "North Atlantic Clinics",
    perfect: "23%",
    good: "23%",
    bad: "23%",
  },
  {
    id: 4,
    practice: "Texas Center Clinics",
    perfect: "15%",
    good: "15%",
    bad: "15%",
  },
  {
    id: 5,
    practice: "North Atlantic Clinics",
    perfect: "12%",
    good: "12%",
    bad: "12%",
  },
  {
    id: 6,
    practice: "Detroit Clinics",
    perfect: "14%",
    good: "14%",
    bad: "14%",
  },
  {
    id: 7,
    practice: "South-West National",
    perfect: "18%",
    good: "18%",
    bad: "18%",
  },
  {
    id: 8,
    practice: "San-Francisco Clinics",
    perfect: "25%",
    good: "25%",
    bad: "25%",
  },
  {
    id: 9,
    practice: "Western Medical Department",
    perfect: "20%",
    good: "20%",
    bad: "20%",
  },
  {
    id: 10,
    practice: "South-West National",
    perfect: "22%",
    good: "22%",
    bad: "22%",
  },
];

export const techData = [
  {
    id: 0,
    tech: "Jimmy Cutler",
    perfect: "25%",
    good: "25%",
    bad: "25%",
    issues: "25%"
  },
  {
    id: 1,
    tech: "Marcus Shultz",
    perfect: "20%",
    good: "20%",
    bad: "20%",
    issues: "20%",
  },
  {
    id: 2,
    tech: "Devon Lane",
    perfect: "22%",
    good: "22%",
    bad: "22%",
    issues: "22%",
  },
  {
    id: 3,
    tech: "Rosy Black",
    perfect: "23%",
    good: "23%",
    bad: "23%",
    issues: "23%",
  },
  {
    id: 4,
    tech: "Tiger Woods",
    perfect: "15%",
    good: "15%",
    bad: "15%",
    issues: "15%",
  },
  {
    id: 5,
    tech: "Adriana Smith",
    perfect: "12%",
    good: "12%",
    bad: "12%",
    issues: "12%",
  },
  {
    id: 6,
    tech: "Jane Forester",
    perfect: "14%",
    good: "14%",
    bad: "14%",
    issues: "14%",
  },
  {
    id: 7,
    tech: "Toby McGuire",
    perfect: "18%",
    good: "18%",
    bad: "18%",
    issues: "18%",
  },
  {
    id: 8,
    tech: "Jimmy Cutler",
    perfect: "25%",
    good: "25%",
    bad: "25%",
    issues: "25%",
  },
  {
    id: 9,
    tech: "Wade Warren",
    perfect: "20%",
    good: "20%",
    bad: "20%",
    issues: "20%",
  },
  {
    id: 10,
    tech: "Devon Lane",
    perfect: "22%",
    good: "22%",
    bad: "22%",
    issues: "22%",
  },
];

export const siteColumns = [
  { id: 0, header: "Sites", },
  { id: 1, header: "Perfect", },
  { id: 2, header: "Good", },
  { id: 3, header: "Bad", },
]

export const practiceColumns = [
  { id: 0, header: "Practices", },
  { id: 1, header: "Perfect", },
  { id: 2, header: "Good", },
  { id: 3, header: "Bad", },
]

export const techColumns = [
  { id: 0, header: "Technologists", },
  { id: 1, header: "Perfect", },
  { id: 2, header: "Good", },
  { id: 3, header: "Bad", },
  { id: 4, header: "Issues", },
]