const alphabets = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
const randomAlphabets = () => {
  let countInit = 1
  let totalCount = Math.floor(Math.random() * 2 + 3)
  let str = ''
  do {
    str += alphabets[Math.floor(Math.random() * 26)]
    countInit++
  } while (countInit <= totalCount);
  return str
}
const accGenerator = () => {
  const str = randomAlphabets() + Math.floor(Math.random() * 10000000000)
  return str
}

export const imageModalSliderData = [
  {
    id: 0,
    tech: "Jimmy Cutler",
    images: [
      {
        id: 0,
        url: '/assets/images/model-1.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'Adequate PEC shape', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No motion', status: true },
          { id: 7, title: 'IMF visible', status: true },
          { id: 8, title: 'IMF open', status: true },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
          { id: 11, title: 'Breast centered' },
          { id: 12, title: 'Adequate Compression' },
          { id: 13, title: 'No artifacts' },
        ]
      },
      {
        id: 1,
        url: '/assets/images/model-2.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: false },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'Breast centered' },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
        ]
      },
      {
        id: 2,
        url: '/assets/images/model-3.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: true },
          { id: 2, title: 'Adequate PEC shape', status: false },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', status: false },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
          { id: 9, title: 'Breast centered' },
          { id: 10, title: 'Adequate Compression' },
          { id: 11, title: 'No artifacts' },
        ]
      },
      {
        id: 3,
        url: '/assets/images/model-4.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
        ]
      },
      {
        id: 4,
        url: '/assets/images/model-5.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PNL within 1cm', },
          { id: 1, title: 'PEC muscle reaches PNL', status: true },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
        ]
      },
      {
        id: 5,
        url: '/assets/images/model-6.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: false },
          { id: 1, title: 'No projection over breast', status: true },
          { id: 2, title: 'Nipple in profile', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'Nipple in Midline', status: false },
        ]
      },
      {
        id: 6,
        url: '/assets/images/model-7.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'PEC muscle reaches PNL', },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'No motion', status: false },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'No projection over breast', },
          { id: 10, title: 'Breast centered', status: false },
        ]
      },
      {
        id: 7,
        url: '/assets/images/model-8.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: true },
          { id: 1, title: 'Nipple in profile', status: true },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'PEC muscle reaches PNL', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No projection over breast', },
          { id: 7, title: 'Adequate PEC shape', status: true },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'IMF visible', },
          { id: 10, title: 'No artifacts', status: false },
          { id: 11, title: 'No motion', },
          { id: 12, title: 'IMF open', status: true },
          { id: 13, title: 'Adequate Compression', status: false },
        ]
      },
      {
        id: 8,
        url: '/assets/images/model-9.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'Breast centered', status: false },
          { id: 2, title: 'No less imaged than prion', status: true },
          { id: 3, title: 'No motion', },
          { id: 4, title: 'Nipple in profile', status: false },
          { id: 5, title: 'No skin folds', status: false },
          { id: 6, title: 'Adequate PEC shape', },
          { id: 7, title: 'IMF visible', },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'Adequate Compression', status: true },
        ]
      },
      {
        id: 9,
        url: '/assets/images/model-10.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'No less imaged than prion', status: true },
          { id: 2, title: 'No motion', status: false },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'IMF visible', status: false },
        ]
      },
    ],
    imageQuality: {
      perfect: "25%",
      good: "25%",
      bad: "25%",
      issues: "25%"
    }
  },
  {
    id: 1,
    tech: "Marcus Shultz",
    images: [
      {
        id: 1,
        url: '/assets/images/model-10.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'No less imaged than prion', status: true },
          { id: 2, title: 'No motion', status: false },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'IMF visible', status: false },
        ]
      },
      {
        id: 2,
        url: '/assets/images/model-9.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'Breast centered', status: false },
          { id: 2, title: 'No less imaged than prion', status: true },
          { id: 3, title: 'No motion', },
          { id: 4, title: 'Nipple in profile', status: false },
          { id: 5, title: 'No skin folds', status: false },
          { id: 6, title: 'Adequate PEC shape', },
          { id: 7, title: 'IMF visible', },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'Adequate Compression', status: true },
        ]
      },
      {
        id: 3,
        url: '/assets/images/model-8.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: true },
          { id: 1, title: 'Nipple in profile', status: true },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'PEC muscle reaches PNL', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No projection over breast', },
          { id: 7, title: 'Adequate PEC shape', status: true },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'IMF visible', },
          { id: 10, title: 'No artifacts', status: false },
          { id: 11, title: 'No motion', },
          { id: 12, title: 'IMF open', status: true },
          { id: 13, title: 'Adequate Compression', status: false },
        ]
      },
      {
        id: 4,
        url: '/assets/images/model-7.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'PEC muscle reaches PNL', },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'No motion', status: false },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'No projection over breast', },
          { id: 10, title: 'Breast centered', status: false },
        ]
      },
      {
        id: 5,
        url: '/assets/images/model-6.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: false },
          { id: 1, title: 'No projection over breast', status: true },
          { id: 2, title: 'Nipple in profile', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'Nipple in Midline', status: false },
        ]
      },
      {
        id: 6,
        url: '/assets/images/model-5.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PNL within 1cm', },
          { id: 1, title: 'PEC muscle reaches PNL', status: true },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
        ]
      },
      {
        id: 7,
        url: '/assets/images/model-4.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
        ]
      },
      {
        id: 8,
        url: '/assets/images/model-3.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: true },
          { id: 2, title: 'Adequate PEC shape', status: false },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', status: false },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
          { id: 9, title: 'Breast centered' },
          { id: 10, title: 'Adequate Compression' },
          { id: 11, title: 'No artifacts' },
        ]
      },
      {
        id: 9,
        url: '/assets/images/model-2.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: false },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'Breast centered' },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
        ]
      },
      {
        id: 0,
        url: '/assets/images/model-1.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'Adequate PEC shape', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No motion', status: true },
          { id: 7, title: 'IMF visible', status: true },
          { id: 8, title: 'IMF open', status: true },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
          { id: 11, title: 'Breast centered' },
          { id: 12, title: 'Adequate Compression' },
          { id: 13, title: 'No artifacts' },
        ]
      },









    ],
    imageQuality: {
      perfect: "20%",
      good: "20%",
      bad: "20%",
      issues: "20%"
    }
  },
  {
    id: 2,
    tech: "Devon Lane",
    images: [
      {
        id: 0,
        url: '/assets/images/model-5.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PNL within 1cm', },
          { id: 1, title: 'PEC muscle reaches PNL', status: true },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
        ]
      },
      {
        id: 1,
        url: '/assets/images/model-4.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
        ]
      },
      {
        id: 2,
        url: '/assets/images/model-3.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: true },
          { id: 2, title: 'Adequate PEC shape', status: false },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', status: false },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
          { id: 9, title: 'Breast centered' },
          { id: 10, title: 'Adequate Compression' },
          { id: 11, title: 'No artifacts' },
        ]
      },
      {
        id: 3,
        url: '/assets/images/model-2.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: false },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'Breast centered' },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
        ]
      },
      {
        id: 4,
        url: '/assets/images/model-1.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'Adequate PEC shape', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No motion', status: true },
          { id: 7, title: 'IMF visible', status: true },
          { id: 8, title: 'IMF open', status: true },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
          { id: 11, title: 'Breast centered' },
          { id: 12, title: 'Adequate Compression' },
          { id: 13, title: 'No artifacts' },
        ]
      },
      {
        id: 5,
        url: '/assets/images/model-7.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'PEC muscle reaches PNL', },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'No motion', status: false },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'No projection over breast', },
          { id: 10, title: 'Breast centered', status: false },
        ]
      },
      {
        id: 6,
        url: '/assets/images/model-8.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: true },
          { id: 1, title: 'Nipple in profile', status: true },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'PEC muscle reaches PNL', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No projection over breast', },
          { id: 7, title: 'Adequate PEC shape', status: true },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'IMF visible', },
          { id: 10, title: 'No artifacts', status: false },
          { id: 11, title: 'No motion', },
          { id: 12, title: 'IMF open', status: true },
          { id: 13, title: 'Adequate Compression', status: false },
        ]
      },
      {
        id: 7,
        url: '/assets/images/model-9.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'Breast centered', status: false },
          { id: 2, title: 'No less imaged than prion', status: true },
          { id: 3, title: 'No motion', },
          { id: 4, title: 'Nipple in profile', status: false },
          { id: 5, title: 'No skin folds', status: false },
          { id: 6, title: 'Adequate PEC shape', },
          { id: 7, title: 'IMF visible', },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'Adequate Compression', status: true },
        ]
      },
      {
        id: 8,
        url: '/assets/images/model-10.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'No less imaged than prion', status: true },
          { id: 2, title: 'No motion', status: false },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'IMF visible', status: false },
        ]
      },
      {
        id: 9,
        url: '/assets/images/model-6.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: false },
          { id: 1, title: 'No projection over breast', status: true },
          { id: 2, title: 'Nipple in profile', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'Nipple in Midline', status: false },
        ]
      },




    ],
    imageQuality: {
      perfect: "22%",
      good: "22%",
      bad: "22%",
      issues: "22%"
    }
  },
  {
    id: 3,
    tech: "Rosy Black",
    images: [
      {
        id: 0,
        url: '/assets/images/model-2.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: false },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'Breast centered' },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
        ]
      },
      {
        id: 1,
        url: '/assets/images/model-1.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'Adequate PEC shape', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No motion', status: true },
          { id: 7, title: 'IMF visible', status: true },
          { id: 8, title: 'IMF open', status: true },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
          { id: 11, title: 'Breast centered' },
          { id: 12, title: 'Adequate Compression' },
          { id: 13, title: 'No artifacts' },
        ]
      },
      {
        id: 2,
        url: '/assets/images/model-4.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
        ]
      },
      {
        id: 3,
        url: '/assets/images/model-3.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: true },
          { id: 2, title: 'Adequate PEC shape', status: false },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', status: false },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
          { id: 9, title: 'Breast centered' },
          { id: 10, title: 'Adequate Compression' },
          { id: 11, title: 'No artifacts' },
        ]
      },
      {
        id: 4,
        url: '/assets/images/model-6.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: false },
          { id: 1, title: 'No projection over breast', status: true },
          { id: 2, title: 'Nipple in profile', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'Nipple in Midline', status: false },
        ]
      },
      {
        id: 5,
        url: '/assets/images/model-5.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PNL within 1cm', },
          { id: 1, title: 'PEC muscle reaches PNL', status: true },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
        ]
      },
      {
        id: 6,
        url: '/assets/images/model-8.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: true },
          { id: 1, title: 'Nipple in profile', status: true },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'PEC muscle reaches PNL', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No projection over breast', },
          { id: 7, title: 'Adequate PEC shape', status: true },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'IMF visible', },
          { id: 10, title: 'No artifacts', status: false },
          { id: 11, title: 'No motion', },
          { id: 12, title: 'IMF open', status: true },
          { id: 13, title: 'Adequate Compression', status: false },
        ]
      },
      {
        id: 7,
        url: '/assets/images/model-7.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'PEC muscle reaches PNL', },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'No motion', status: false },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'No projection over breast', },
          { id: 10, title: 'Breast centered', status: false },
        ]
      },
      {
        id: 8,
        url: '/assets/images/model-10.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'No less imaged than prion', status: true },
          { id: 2, title: 'No motion', status: false },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'IMF visible', status: false },
        ]
      },
      {
        id: 9,
        url: '/assets/images/model-9.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'Breast centered', status: false },
          { id: 2, title: 'No less imaged than prion', status: true },
          { id: 3, title: 'No motion', },
          { id: 4, title: 'Nipple in profile', status: false },
          { id: 5, title: 'No skin folds', status: false },
          { id: 6, title: 'Adequate PEC shape', },
          { id: 7, title: 'IMF visible', },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'Adequate Compression', status: true },
        ]
      },

    ],
    imageQuality: {
      perfect: "23%",
      good: "23%",
      bad: "23%",
      issues: "23%"
    }
  },
  {
    id: 4,
    tech: "Tiger Woods",
    images: [
      {
        id: 0,
        url: '/assets/images/model-6.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: false },
          { id: 1, title: 'No projection over breast', status: true },
          { id: 2, title: 'Nipple in profile', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'Nipple in Midline', status: false },
        ]
      },
      {
        id: 1,
        url: '/assets/images/model-7.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'PEC muscle reaches PNL', },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'No motion', status: false },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'No projection over breast', },
          { id: 10, title: 'Breast centered', status: false },
        ]
      },
      {
        id: 2,
        url: '/assets/images/model-8.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: true },
          { id: 1, title: 'Nipple in profile', status: true },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'PEC muscle reaches PNL', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No projection over breast', },
          { id: 7, title: 'Adequate PEC shape', status: true },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'IMF visible', },
          { id: 10, title: 'No artifacts', status: false },
          { id: 11, title: 'No motion', },
          { id: 12, title: 'IMF open', status: true },
          { id: 13, title: 'Adequate Compression', status: false },
        ]
      },
      {
        id: 3,
        url: '/assets/images/model-9.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'Breast centered', status: false },
          { id: 2, title: 'No less imaged than prion', status: true },
          { id: 3, title: 'No motion', },
          { id: 4, title: 'Nipple in profile', status: false },
          { id: 5, title: 'No skin folds', status: false },
          { id: 6, title: 'Adequate PEC shape', },
          { id: 7, title: 'IMF visible', },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'Adequate Compression', status: true },
        ]
      },
      {
        id: 4,
        url: '/assets/images/model-10.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'No less imaged than prion', status: true },
          { id: 2, title: 'No motion', status: false },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'IMF visible', status: false },
        ]
      },
      {
        id: 5,
        url: '/assets/images/model-1.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'Adequate PEC shape', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No motion', status: true },
          { id: 7, title: 'IMF visible', status: true },
          { id: 8, title: 'IMF open', status: true },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
          { id: 11, title: 'Breast centered' },
          { id: 12, title: 'Adequate Compression' },
          { id: 13, title: 'No artifacts' },
        ]
      },
      {
        id: 6,
        url: '/assets/images/model-2.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: false },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'Breast centered' },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
        ]
      },
      {
        id: 7,
        url: '/assets/images/model-3.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: true },
          { id: 2, title: 'Adequate PEC shape', status: false },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', status: false },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
          { id: 9, title: 'Breast centered' },
          { id: 10, title: 'Adequate Compression' },
          { id: 11, title: 'No artifacts' },
        ]
      },
      {
        id: 8,
        url: '/assets/images/model-4.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
        ]
      },
      {
        id: 9,
        url: '/assets/images/model-5.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PNL within 1cm', },
          { id: 1, title: 'PEC muscle reaches PNL', status: true },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
        ]
      },
    ],
    imageQuality: {
      perfect: "15%",
      good: "15%",
      bad: "15%",
      issues: "15%"
    }
  },
  {
    id: 5,
    tech: "Adriana Smith",
    images: [
      {
        id: 0,
        url: '/assets/images/model-2.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: false },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'Breast centered' },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
        ]
      },
      {
        id: 1,
        url: '/assets/images/model-4.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
        ]
      },
      {
        id: 2,
        url: '/assets/images/model-1.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'Adequate PEC shape', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No motion', status: true },
          { id: 7, title: 'IMF visible', status: true },
          { id: 8, title: 'IMF open', status: true },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
          { id: 11, title: 'Breast centered' },
          { id: 12, title: 'Adequate Compression' },
          { id: 13, title: 'No artifacts' },
        ]
      },
      {
        id: 3,
        url: '/assets/images/model-3.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: true },
          { id: 2, title: 'Adequate PEC shape', status: false },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', status: false },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
          { id: 9, title: 'Breast centered' },
          { id: 10, title: 'Adequate Compression' },
          { id: 11, title: 'No artifacts' },
        ]
      },
      {
        id: 4,
        url: '/assets/images/model-7.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'PEC muscle reaches PNL', },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'No motion', status: false },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'No projection over breast', },
          { id: 10, title: 'Breast centered', status: false },
        ]
      },
      {
        id: 5,
        url: '/assets/images/model-8.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: true },
          { id: 1, title: 'Nipple in profile', status: true },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'PEC muscle reaches PNL', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No projection over breast', },
          { id: 7, title: 'Adequate PEC shape', status: true },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'IMF visible', },
          { id: 10, title: 'No artifacts', status: false },
          { id: 11, title: 'No motion', },
          { id: 12, title: 'IMF open', status: true },
          { id: 13, title: 'Adequate Compression', status: false },
        ]
      },
      {
        id: 6,
        url: '/assets/images/model-5.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PNL within 1cm', },
          { id: 1, title: 'PEC muscle reaches PNL', status: true },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
        ]
      },
      {
        id: 7,
        url: '/assets/images/model-6.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: false },
          { id: 1, title: 'No projection over breast', status: true },
          { id: 2, title: 'Nipple in profile', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'Nipple in Midline', status: false },
        ]
      },
      {
        id: 8,
        url: '/assets/images/model-10.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'No less imaged than prion', status: true },
          { id: 2, title: 'No motion', status: false },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'IMF visible', status: false },
        ]
      },
      {
        id: 9,
        url: '/assets/images/model-9.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'Breast centered', status: false },
          { id: 2, title: 'No less imaged than prion', status: true },
          { id: 3, title: 'No motion', },
          { id: 4, title: 'Nipple in profile', status: false },
          { id: 5, title: 'No skin folds', status: false },
          { id: 6, title: 'Adequate PEC shape', },
          { id: 7, title: 'IMF visible', },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'Adequate Compression', status: true },
        ]
      },
    ],
    imageQuality: {
      perfect: "12%",
      good: "12%",
      bad: "12%",
      issues: "12%"
    }
  },
  {
    id: 6,
    tech: "Jane Forester",
    images: [
      {
        id: 0,
        url: '/assets/images/model-1.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'Adequate PEC shape', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No motion', status: true },
          { id: 7, title: 'IMF visible', status: true },
          { id: 8, title: 'IMF open', status: true },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
          { id: 11, title: 'Breast centered' },
          { id: 12, title: 'Adequate Compression' },
          { id: 13, title: 'No artifacts' },
        ]
      },
      {
        id: 1,
        url: '/assets/images/model-2.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: false },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'Breast centered' },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
        ]
      },
      {
        id: 2,
        url: '/assets/images/model-3.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: true },
          { id: 2, title: 'Adequate PEC shape', status: false },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', status: false },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
          { id: 9, title: 'Breast centered' },
          { id: 10, title: 'Adequate Compression' },
          { id: 11, title: 'No artifacts' },
        ]
      },
      {
        id: 3,
        url: '/assets/images/model-4.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
        ]
      },
      {
        id: 4,
        url: '/assets/images/model-5.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PNL within 1cm', },
          { id: 1, title: 'PEC muscle reaches PNL', status: true },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
        ]
      },
      {
        id: 5,
        url: '/assets/images/model-6.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: false },
          { id: 1, title: 'No projection over breast', status: true },
          { id: 2, title: 'Nipple in profile', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'Nipple in Midline', status: false },
        ]
      },
      {
        id: 6,
        url: '/assets/images/model-7.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'PEC muscle reaches PNL', },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'No motion', status: false },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'No projection over breast', },
          { id: 10, title: 'Breast centered', status: false },
        ]
      },
      {
        id: 7,
        url: '/assets/images/model-8.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: true },
          { id: 1, title: 'Nipple in profile', status: true },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'PEC muscle reaches PNL', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No projection over breast', },
          { id: 7, title: 'Adequate PEC shape', status: true },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'IMF visible', },
          { id: 10, title: 'No artifacts', status: false },
          { id: 11, title: 'No motion', },
          { id: 12, title: 'IMF open', status: true },
          { id: 13, title: 'Adequate Compression', status: false },
        ]
      },
      {
        id: 8,
        url: '/assets/images/model-9.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'Breast centered', status: false },
          { id: 2, title: 'No less imaged than prion', status: true },
          { id: 3, title: 'No motion', },
          { id: 4, title: 'Nipple in profile', status: false },
          { id: 5, title: 'No skin folds', status: false },
          { id: 6, title: 'Adequate PEC shape', },
          { id: 7, title: 'IMF visible', },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'Adequate Compression', status: true },
        ]
      },
      {
        id: 9,
        url: '/assets/images/model-10.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'No less imaged than prion', status: true },
          { id: 2, title: 'No motion', status: false },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'IMF visible', status: false },
        ]
      },
    ],
    imageQuality: {
      perfect: "14%",
      good: "14%",
      bad: "14%",
      issues: "14%"
    }
  },
  {
    id: 7,
    tech: "Toby McGuire",
    images: [
      {
        id: 0,
        url: '/assets/images/model-2.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: false },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'Breast centered' },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
        ]
      },
      {
        id: 1,
        url: '/assets/images/model-6.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: false },
          { id: 1, title: 'No projection over breast', status: true },
          { id: 2, title: 'Nipple in profile', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'Nipple in Midline', status: false },
        ]
      },
      {
        id: 2,
        url: '/assets/images/model-1.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'Adequate PEC shape', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No motion', status: true },
          { id: 7, title: 'IMF visible', status: true },
          { id: 8, title: 'IMF open', status: true },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
          { id: 11, title: 'Breast centered' },
          { id: 12, title: 'Adequate Compression' },
          { id: 13, title: 'No artifacts' },
        ]
      },
      {
        id: 3,
        url: '/assets/images/model-5.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PNL within 1cm', },
          { id: 1, title: 'PEC muscle reaches PNL', status: true },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
        ]
      },
      {
        id: 4,
        url: '/assets/images/model-4.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
        ]
      },
      {
        id: 5,
        url: '/assets/images/model-3.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: true },
          { id: 2, title: 'Adequate PEC shape', status: false },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', status: false },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
          { id: 9, title: 'Breast centered' },
          { id: 10, title: 'Adequate Compression' },
          { id: 11, title: 'No artifacts' },
        ]
      },
      {
        id: 6,
        url: '/assets/images/model-10.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'No less imaged than prion', status: true },
          { id: 2, title: 'No motion', status: false },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'IMF visible', status: false },
        ]
      },
      {
        id: 7,
        url: '/assets/images/model-9.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'Breast centered', status: false },
          { id: 2, title: 'No less imaged than prion', status: true },
          { id: 3, title: 'No motion', },
          { id: 4, title: 'Nipple in profile', status: false },
          { id: 5, title: 'No skin folds', status: false },
          { id: 6, title: 'Adequate PEC shape', },
          { id: 7, title: 'IMF visible', },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'Adequate Compression', status: true },
        ]
      },
      {
        id: 8,
        url: '/assets/images/model-8.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: true },
          { id: 1, title: 'Nipple in profile', status: true },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'PEC muscle reaches PNL', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No projection over breast', },
          { id: 7, title: 'Adequate PEC shape', status: true },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'IMF visible', },
          { id: 10, title: 'No artifacts', status: false },
          { id: 11, title: 'No motion', },
          { id: 12, title: 'IMF open', status: true },
          { id: 13, title: 'Adequate Compression', status: false },
        ]
      },
      {
        id: 9,
        url: '/assets/images/model-7.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'PEC muscle reaches PNL', },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'No motion', status: false },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'No projection over breast', },
          { id: 10, title: 'Breast centered', status: false },
        ]
      },
    ],
    imageQuality: {
      perfect: "18%",
      good: "18%",
      bad: "18%",
      issues: "18%"
    }
  },
  {
    id: 8,
    tech: "Jimmy Cutler",
    images: [
      {
        id: 0,
        url: '/assets/images/model-9.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'Breast centered', status: false },
          { id: 2, title: 'No less imaged than prion', status: true },
          { id: 3, title: 'No motion', },
          { id: 4, title: 'Nipple in profile', status: false },
          { id: 5, title: 'No skin folds', status: false },
          { id: 6, title: 'Adequate PEC shape', },
          { id: 7, title: 'IMF visible', },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'Adequate Compression', status: true },
        ]
      },
      {
        id: 1,
        url: '/assets/images/model-8.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: true },
          { id: 1, title: 'Nipple in profile', status: true },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'PEC muscle reaches PNL', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No projection over breast', },
          { id: 7, title: 'Adequate PEC shape', status: true },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'IMF visible', },
          { id: 10, title: 'No artifacts', status: false },
          { id: 11, title: 'No motion', },
          { id: 12, title: 'IMF open', status: true },
          { id: 13, title: 'Adequate Compression', status: false },
        ]
      },
      {
        id: 2,
        url: '/assets/images/model-6.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: false },
          { id: 1, title: 'No projection over breast', status: true },
          { id: 2, title: 'Nipple in profile', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'Nipple in Midline', status: false },
        ]
      },
      {
        id: 3,
        url: '/assets/images/model-10.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'No less imaged than prion', status: true },
          { id: 2, title: 'No motion', status: false },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'IMF visible', status: false },
        ]
      },
      {
        id: 4,
        url: '/assets/images/model-7.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'PEC muscle reaches PNL', },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'No motion', status: false },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'No projection over breast', },
          { id: 10, title: 'Breast centered', status: false },
        ]
      },
      {
        id: 5,
        url: '/assets/images/model-4.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
        ]
      },
      {
        id: 6,
        url: '/assets/images/model-1.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'Adequate PEC shape', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No motion', status: true },
          { id: 7, title: 'IMF visible', status: true },
          { id: 8, title: 'IMF open', status: true },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
          { id: 11, title: 'Breast centered' },
          { id: 12, title: 'Adequate Compression' },
          { id: 13, title: 'No artifacts' },
        ]
      },
      {
        id: 7,
        url: '/assets/images/model-5.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PNL within 1cm', },
          { id: 1, title: 'PEC muscle reaches PNL', status: true },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
        ]
      },
      {
        id: 8,
        url: '/assets/images/model-3.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: true },
          { id: 2, title: 'Adequate PEC shape', status: false },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', status: false },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
          { id: 9, title: 'Breast centered' },
          { id: 10, title: 'Adequate Compression' },
          { id: 11, title: 'No artifacts' },
        ]
      },
      {
        id: 9,
        url: '/assets/images/model-2.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: false },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'Breast centered' },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
        ]
      },
    ],
    imageQuality: {
      perfect: "25%",
      good: "25%",
      bad: "25%",
      issues: "25%"
    }
  },
  {
    id: 9,
    tech: "Wade Warren",
    images: [
      {
        id: 0,
        url: '/assets/images/model-4.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
        ]
      },
      {
        id: 1,
        url: '/assets/images/model-5.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PNL within 1cm', },
          { id: 1, title: 'PEC muscle reaches PNL', status: true },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
        ]
      },
      {
        id: 2,
        url: '/assets/images/model-8.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: true },
          { id: 1, title: 'Nipple in profile', status: true },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'PEC muscle reaches PNL', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No projection over breast', },
          { id: 7, title: 'Adequate PEC shape', status: true },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'IMF visible', },
          { id: 10, title: 'No artifacts', status: false },
          { id: 11, title: 'No motion', },
          { id: 12, title: 'IMF open', status: true },
          { id: 13, title: 'Adequate Compression', status: false },
        ]
      },
      {
        id: 3,
        url: '/assets/images/model-6.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: false },
          { id: 1, title: 'No projection over breast', status: true },
          { id: 2, title: 'Nipple in profile', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'Nipple in Midline', status: false },
        ]
      },
      {
        id: 4,
        url: '/assets/images/model-1.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'Adequate PEC shape', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No motion', status: true },
          { id: 7, title: 'IMF visible', status: true },
          { id: 8, title: 'IMF open', status: true },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
          { id: 11, title: 'Breast centered' },
          { id: 12, title: 'Adequate Compression' },
          { id: 13, title: 'No artifacts' },
        ]
      },
      {
        id: 5,
        url: '/assets/images/model-10.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'No less imaged than prion', status: true },
          { id: 2, title: 'No motion', status: false },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'IMF visible', status: false },
        ]
      },
      {
        id: 6,
        url: '/assets/images/model-2.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: false },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'Breast centered' },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
        ]
      },
      {
        id: 7,
        url: '/assets/images/model-9.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'Breast centered', status: false },
          { id: 2, title: 'No less imaged than prion', status: true },
          { id: 3, title: 'No motion', },
          { id: 4, title: 'Nipple in profile', status: false },
          { id: 5, title: 'No skin folds', status: false },
          { id: 6, title: 'Adequate PEC shape', },
          { id: 7, title: 'IMF visible', },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'Adequate Compression', status: true },
        ]
      },
      {
        id: 8,
        url: '/assets/images/model-3.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: true },
          { id: 2, title: 'Adequate PEC shape', status: false },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', status: false },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
          { id: 9, title: 'Breast centered' },
          { id: 10, title: 'Adequate Compression' },
          { id: 11, title: 'No artifacts' },
        ]
      },
      {
        id: 9,
        url: '/assets/images/model-7.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'PEC muscle reaches PNL', },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'No motion', status: false },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'No projection over breast', },
          { id: 10, title: 'Breast centered', status: false },
        ]
      },
    ],
    imageQuality: {
      perfect: "20%",
      good: "20%",
      bad: "20%",
      issues: "20%"
    }
  },
  {
    id: 10,
    tech: "Devon Lane",
    images: [
      {
        id: 4,
        url: '/assets/images/model-5.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PNL within 1cm', },
          { id: 1, title: 'PEC muscle reaches PNL', status: true },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
        ]
      },
      {
        id: 3,
        url: '/assets/images/model-4.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'Adequate PEC shape', status: true },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
        ]
      },
      {
        id: 7,
        url: '/assets/images/model-8.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: true },
          { id: 1, title: 'Nipple in profile', status: true },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'PEC muscle reaches PNL', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No projection over breast', },
          { id: 7, title: 'Adequate PEC shape', status: true },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'IMF visible', },
          { id: 10, title: 'No artifacts', status: false },
          { id: 11, title: 'No motion', },
          { id: 12, title: 'IMF open', status: true },
          { id: 13, title: 'Adequate Compression', status: false },
        ]
      },
      {
        id: 1,
        url: '/assets/images/model-2.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: false },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'Breast centered' },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
        ]
      },
      {
        id: 0,
        url: '/assets/images/model-1.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: false },
          { id: 1, title: 'Nipple in Midline', status: false },
          { id: 2, title: 'PEC muscle reaches PNL', status: true },
          { id: 3, title: 'PNL within 1cm', status: true },
          { id: 4, title: 'Adequate PEC shape', status: true },
          { id: 5, title: 'No skin folds', status: true },
          { id: 6, title: 'No motion', status: true },
          { id: 7, title: 'IMF visible', status: true },
          { id: 8, title: 'IMF open', status: true },
          { id: 9, title: 'No less imaged than prion', status: true },
          { id: 10, title: 'No projection over breast', status: true },
          { id: 11, title: 'Breast centered' },
          { id: 12, title: 'Adequate Compression' },
          { id: 13, title: 'No artifacts' },
        ]
      },
      {
        id: 9,
        url: '/assets/images/model-10.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'No less imaged than prion', status: true },
          { id: 2, title: 'No motion', status: false },
          { id: 3, title: 'No skin folds', status: false },
          { id: 4, title: 'IMF visible', status: false },
        ]
      },
      {
        id: 8,
        url: '/assets/images/model-9.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'PEC muscle reaches PNL', status: true },
          { id: 1, title: 'Breast centered', status: false },
          { id: 2, title: 'No less imaged than prion', status: true },
          { id: 3, title: 'No motion', },
          { id: 4, title: 'Nipple in profile', status: false },
          { id: 5, title: 'No skin folds', status: false },
          { id: 6, title: 'Adequate PEC shape', },
          { id: 7, title: 'IMF visible', },
          { id: 8, title: 'IMF open', status: false },
          { id: 9, title: 'Adequate Compression', status: true },
        ]
      },
      {
        id: 2,
        url: '/assets/images/model-3.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'Nipple in Midline', status: true },
          { id: 2, title: 'Adequate PEC shape', status: false },
          { id: 3, title: 'No skin folds', status: true },
          { id: 4, title: 'No motion', status: true },
          { id: 5, title: 'IMF visible', status: false },
          { id: 6, title: 'IMF open', status: true },
          { id: 7, title: 'No less imaged than prion', },
          { id: 8, title: 'No projection over breast', status: false },
          { id: 9, title: 'Breast centered' },
          { id: 10, title: 'Adequate Compression' },
          { id: 11, title: 'No artifacts' },
        ]
      },
      {
        id: 6,
        url: '/assets/images/model-7.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Nipple in profile', status: true },
          { id: 1, title: 'PEC muscle reaches PNL', },
          { id: 2, title: 'Nipple in Midline', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'IMF visible', status: true },
          { id: 6, title: 'No motion', status: false },
          { id: 7, title: 'Adequate Compression' },
          { id: 8, title: 'No less imaged than prion', status: true },
          { id: 9, title: 'No projection over breast', },
          { id: 10, title: 'Breast centered', status: false },
        ]
      },
      {
        id: 5,
        url: '/assets/images/model-6.png',
        acc: `${accGenerator()}`,
        view: `${randomAlphabets()}`,
        issues: [
          { id: 0, title: 'Breast centered', status: false },
          { id: 1, title: 'No projection over breast', status: true },
          { id: 2, title: 'Nipple in profile', status: false },
          { id: 3, title: 'Adequate PEC shape', status: true },
          { id: 4, title: 'No skin folds', status: true },
          { id: 5, title: 'Nipple in Midline', status: false },
        ]
      },
    ],
    imageQuality: {
      perfect: "22%",
      good: "22%",
      bad: "22%",
      issues: "22%"
    }
  },
]

export const images = [
  {
    id: 0,
    url: 'https://drive.google.com/uc?export=view&id=1e1LTe0_M-KCWZFB8vep1LzxiUB5gxf18',
    acc: `${accGenerator()}`,
    view: `${randomAlphabets()}`,
    tech: 'Morgan Johnson',
    issues: [
      { id: 0, title: 'Nipple in profile', status: false },
      { id: 1, title: 'Nipple in Midline', status: false },
      { id: 2, title: 'PEC muscle reaches PNL', status: true },
      { id: 3, title: 'PNL within 1cm', status: true },
      { id: 4, title: 'Adequate PEC shape', status: true },
      { id: 5, title: 'No skin folds', status: true },
      { id: 6, title: 'No motion', status: true },
      { id: 7, title: 'IMF visible', status: true },
      { id: 8, title: 'IMF open', status: true },
      { id: 9, title: 'No less imaged than prion', status: true },
      { id: 10, title: 'No projection over breast', status: true },
      { id: 11, title: 'Breast centered' },
      { id: 12, title: 'Adequate Compression' },
      { id: 13, title: 'No artifacts' },
    ],
  },
  {
    id: 1,
    url: 'https://drive.google.com/uc?export=view&id=1YvkDxFPbfwwKf6ImDAno_gAM3m9U90zW',
    acc: `${accGenerator()}`,
    view: `${randomAlphabets()}`,
    tech: 'Jimmy Cutler',
    issues: [
      { id: 0, title: 'Nipple in profile', status: false },
      { id: 1, title: 'Nipple in Midline', status: false },
      { id: 2, title: 'PEC muscle reaches PNL', status: true },
      { id: 3, title: 'No skin folds', status: true },
      { id: 4, title: 'No motion', status: false },
      { id: 5, title: 'IMF visible', status: true },
      { id: 6, title: 'Breast centered' },
      { id: 7, title: 'Adequate Compression' },
      { id: 8, title: 'IMF open', status: false },
      { id: 9, title: 'No less imaged than prion', status: true },
      { id: 10, title: 'No projection over breast', status: true },
    ],
  },
  {
    id: 2,
    url: 'https://drive.google.com/uc?export=view&id=1GJcmeSxPDegvIKUWnLn9A19Rxc8CXKIY',
    acc: `${accGenerator()}`,
    view: `${randomAlphabets()}`,
    tech: 'Marcus Shultz',
    issues: [
      { id: 0, title: 'Nipple in profile', status: true },
      { id: 1, title: 'Nipple in Midline', status: true },
      { id: 2, title: 'Adequate PEC shape', status: false },
      { id: 3, title: 'No skin folds', status: true },
      { id: 4, title: 'No motion', status: true },
      { id: 5, title: 'IMF visible', status: false },
      { id: 6, title: 'IMF open', status: true },
      { id: 7, title: 'No less imaged than prion' },
      { id: 8, title: 'No projection over breast', status: false },
      { id: 9, title: 'Breast centered' },
      { id: 10, title: 'Adequate Compression' },
      { id: 11, title: 'No artifacts' },
    ],
  },
  {
    id: 3,
    url: 'https://drive.google.com/uc?export=view&id=10671QWNVUZF6hEYEdzMsZoYEOSyEpidf',
    acc: `${accGenerator()}`,
    view: `${randomAlphabets()}`,
    tech: 'Devon Lane',
    issues: [
      { id: 0, title: 'Nipple in profile', status: true },
      { id: 1, title: 'Nipple in Midline', status: false },
      { id: 2, title: 'Adequate PEC shape', status: true },
      { id: 3, title: 'No skin folds', status: false },
      { id: 4, title: 'No motion', status: true },
      { id: 5, title: 'IMF visible' },
      { id: 6, title: 'IMF open', status: true },
      { id: 7, title: 'No less imaged than prion' },
      { id: 8, title: 'No projection over breast', status: false },
    ],
  },
  {
    id: 4,
    url: 'https://drive.google.com/uc?export=view&id=13OYYaecw2EiDOcmlL8ck1A1gsytn3IK-',
    acc: `${accGenerator()}`,
    view: `${randomAlphabets()}`,
    tech: 'Rosy Black',
    issues: [
      { id: 0, title: 'PNL within 1cm' },
      { id: 1, title: 'PEC muscle reaches PNL', status: true },
      { id: 2, title: 'Adequate PEC shape', status: true },
      { id: 3, title: 'No skin folds', status: false },
    ],
  },
  {
    id: 5,
    url: 'https://drive.google.com/uc?export=view&id=1y-M5UXGeaQU1j-KLhnIAp6EzqC-F6tVG',
    acc: `${accGenerator()}`,
    view: `${randomAlphabets()}`,
    tech: 'Tiger Woods',
    issues: [
      { id: 0, title: 'Breast centered', status: false },
      { id: 1, title: 'No projection over breast', status: true },
      { id: 2, title: 'Nipple in profile', status: false },
      { id: 3, title: 'Adequate PEC shape', status: true },
      { id: 4, title: 'No skin folds', status: true },
      { id: 5, title: 'Nipple in Midline', status: false },
    ],
  },
  {
    id: 6,
    url: 'https://drive.google.com/uc?export=view&id=180zpf_2ifECIG7ky4ldZHtM14AX_a-83',
    acc: `${accGenerator()}`,
    view: `${randomAlphabets()}`,
    tech: 'Adriana Smith',
    issues: [
      { id: 0, title: 'Nipple in profile', status: true },
      { id: 1, title: 'PEC muscle reaches PNL' },
      { id: 2, title: 'Nipple in Midline', status: false },
      { id: 3, title: 'Adequate PEC shape', status: true },
      { id: 4, title: 'No skin folds', status: true },
      { id: 5, title: 'IMF visible', status: true },
      { id: 6, title: 'No motion', status: false },
      { id: 7, title: 'Adequate Compression' },
      { id: 8, title: 'No less imaged than prion', status: true },
      { id: 9, title: 'No projection over breast' },
      { id: 10, title: 'Breast centered', status: false },
    ],
  },
  {
    id: 7,
    url: 'https://drive.google.com/uc?export=view&id=1aYc5jXX8Iii0-3jdOLdimp4ZxNohl7en',
    acc: `${accGenerator()}`,
    view: `${randomAlphabets()}`,
    tech: 'Jane Forester',
    issues: [
      { id: 0, title: 'Breast centered', status: true },
      { id: 1, title: 'Nipple in profile', status: true },
      { id: 2, title: 'Nipple in Midline', status: false },
      { id: 3, title: 'PNL within 1cm', status: true },
      { id: 4, title: 'PEC muscle reaches PNL', status: true },
      { id: 5, title: 'No skin folds', status: true },
      { id: 6, title: 'No projection over breast' },
      { id: 7, title: 'Adequate PEC shape', status: true },
      { id: 8, title: 'No less imaged than prion', status: true },
      { id: 9, title: 'IMF visible' },
      { id: 10, title: 'No artifacts', status: false },
      { id: 11, title: 'No motion' },
      { id: 12, title: 'IMF open', status: true },
      { id: 13, title: 'Adequate Compression', status: false },
    ],
  },
  {
    id: 8,
    url: 'https://drive.google.com/uc?export=view&id=15ZjgmiLJ3uusg9zvl74fcD2aT_j5edM_',
    acc: `${accGenerator()}`,
    view: `${randomAlphabets()}`,
    tech: 'Toby McGuire',
    issues: [
      { id: 0, title: 'PEC muscle reaches PNL', status: true },
      { id: 1, title: 'Breast centered', status: false },
      { id: 2, title: 'No less imaged than prion', status: true },
      { id: 3, title: 'No motion' },
      { id: 4, title: 'Nipple in profile', status: false },
      { id: 5, title: 'No skin folds', status: false },
      { id: 6, title: 'Adequate PEC shape' },
      { id: 7, title: 'IMF visible' },
      { id: 8, title: 'IMF open', status: false },
      { id: 9, title: 'Adequate Compression', status: true },
    ],
  },
  {
    id: 9,
    url: 'https://drive.google.com/uc?export=view&id=1S2ZyWpbjfLJBGiQ3Wl5hIZ9maNcbILxI',
    acc: `${accGenerator()}`,
    view: `${randomAlphabets()}`,
    tech: 'Wade Warren',
    issues: [
      { id: 0, title: 'PEC muscle reaches PNL', status: true },
      { id: 1, title: 'No less imaged than prion', status: true },
      { id: 2, title: 'No motion', status: false },
      { id: 3, title: 'No skin folds', status: false },
      { id: 4, title: 'IMF visible', status: false },
    ],
  },
]